routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('resultado', [App\Http\Controllers\HomeController::class, 'busqueda'])->name('resultado');
Route::get('vistaprevia', [App\Http\Controllers\HomeController::class, 'vistaprevia'])->name('vistaprevia');
Route::post('gprecios', [App\Http\Controllers\PreciosController::class, 'gprecios'])->name('gprecios.post');
Route::post('tprecios', [App\Http\Controllers\PreciosController::class, 'tprecios'])->name('tprecios.post');
Route::post('lprecios', [App\Http\Controllers\PreciosController::class, 'lprecios'])->name('lprecios.post');
Route::post('clayout', [App\Http\Controllers\TuwallController::class, 'clayout'])->name('clayout.post');
Route::get('carrito', [App\Http\Controllers\HomeController::class, 'carrito'])->name('carrito');
Route::get('confirmacion', [App\Http\Controllers\HomeController::class, 'confirmacion'])->name('confirmacion');
//Route::get('carrito', ['middleware' => 'auth', 'uses' => 'App\Http\Controllers\HomeController@carrito'], [App\Http\Controllers\HomeController::class, 'carrito'])->name('carrito');

Route::get('tuwall', [App\Http\Controllers\TuwallController::class, 'tuwall'])->name('tuwall');
Route::post('cmarco', [App\Http\Controllers\TuwallController::class, 'cmarco'])->name('cmarco');
Route::post('clayout', [App\Http\Controllers\TuwallController::class, 'clayout'])->name('clayout');
Route::get('talentos', [App\Http\Controllers\TalentosController::class, 'talentos'])->name('talentos');
Route::resource('contacto', App\Http\Controllers\ContactoController::class);
Route::get('carga', [App\Http\Controllers\HomeController::class, 'carga'])->name('carga');
Route::resource('registro', App\Http\Controllers\RegistroController::class);
Route::post('registra', [App\Http\Controllers\RegistraController::class, 'registra'])->name('registra.post');


Route::get('/clear-cache', function () {
    echo Artisan::call('config:clear');
    echo Artisan::call('config:cache');
    echo Artisan::call('cache:clear');
    echo Artisan::call('route:clear');
    echo Artisan::call('optimize:clear');
 });


Auth::routes();

Route::group(['prefix' => 'usuario', 'middleware' => ['role:admin|operativo|cliente']], function(){
    Route::get('/', [App\Http\Controllers\Usuario\HomeController::class, 'index']);
    Route::get('confirmacion', [App\Http\Controllers\Usuario\HomeController::class, 'confirmacion']);
    Route::resource('carrito', App\Http\Controllers\Usuario\CarritoController::class);
    Route::resource('cgetty',  App\Http\Controllers\Usuario\CgettyController::class);
    Route::resource('tuwall',  App\Http\Controllers\Usuario\TuwallController::class);
    Route::get('pago', [App\Http\Controllers\Usuario\PagoController::class, 'pago'])->name('pago');
});

Route::get('api', [App\Http\Controllers\Api\GettyController::class, 'getty'])->name('getty');

Route::group(['prefix' => 'admin','middleware' => ['role:admin|operativo|cliente']], function(){
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
    Route::resource('sliders', App\Http\Controllers\Admin\SlidersController::class);
    Route::resource('usuarios', App\Http\Controllers\Admin\UsersController::class);
    Route::get('reportes', [App\Http\Controllers\ReportesController::class, 'index'])->name('reportes');
    Route::resource('atributos', App\Http\Controllers\AtributosController::class);
    Route::get('getty', [App\Http\Controllers\Admin\GettyController::class, 'getty'])->name('api');
    Route::post('search',[App\Http\Controllers\Admin\GettyController::class, 'search'])->name('search.post');
    Route::resource('materiales', App\Http\Controllers\Admin\MaterialesController::class);
    Route::resource('medidas', App\Http\Controllers\Admin\MedidasController::class);
    Route::resource('categorias', App\Http\Controllers\Admin\CategoriasController::class);
    Route::resource('colecciones', App\Http\Controllers\Admin\ColeccionesController::class);
    Route::resource('clientes', App\Http\Controllers\Admin\ClientesController::class);
    Route::resource('tags', App\Http\Controllers\Admin\TagsController::class);
    Route::resource('contact', App\Http\Controllers\Admin\ContactoController::class);
    Route::resource('ordenes', App\Http\Controllers\Admin\OrdenesController::class);
    Route::resource('perfil', App\Http\Controllers\Admin\PerfilController::class);
    Route::get('precios', [App\Http\Controllers\Admin\PreciosController::class, 'index'])->name('precios');
    Route::post('cupon',[App\Http\Controllers\Admin\CuponesController::class, 'cupon'])->name('cupon.post');
    Route::get('cuponera',[App\Http\Controllers\Admin\CuponesController::class, 'index']);
    Route::get('incompletas',[App\Http\Controllers\Admin\OrdenIncompletaController::class, 'index'])->name('incompletas');
    
    
});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    use HasFactory;

    protected $fillable = ['url'];
}

app/Http/Controllers/Admin/SlidersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Slider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SlidersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::all();
        return view('admin.ecommerce.slider.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.ecommerce.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'file' =>  'required'
        ]);

       $imagenes = $request->file('file')->store('public/sliders');
       $url = Storage::url($imagenes);

       Slider::create([
           'url' => $url
       ]);

       //redirect()->route('admin.ecommerce.slider.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slider $slider)
    {
        //Cambia storage por public para eliminar de storage
        $url = str_replace('storage', 'public', $slider->url);
        //Elimina de storage la imagen
        storage::delete($url);
        //Eliminar de la bd
        $slider->delete();
        return redirect()->route('sliders.index');
    }
}

resources/views/admin/ecommerce/slider/create.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/dropzone.min.css" integrity="sha512-3g+prZHHfmnvE1HBLwUnVuunaPOob7dpksI7/v6UnF/rnKGwHf/GdEq9K7iEN7qTtW+S0iivTcGpeTBqqB04wA==" crossorigin="anonymous" />
@stop



@section('title', 'Sliders')

@section('content_header')
    <h1>Subir imagenes</h1>
@stop


@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
               
                  <form action="{{route('sliders.store')}}" class="dropzone" id="my-awesome-dropzone" method="POST" >
                    @csrf
                 
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"  crossorigin="anonymous"></script>
<script>
    // "myAwesomeDropzone" is the camelized version of the HTML element's ID
Dropzone.options.myAwesomeDropzone = {
  headers:{
      'X-CSRF-TOKEN' : "{{csrf_token()}}"
  },
};
</script>
@stop

resources/views/admin/ecommerce/slider/index.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/dropzone.min.css" integrity="sha512-3g+prZHHfmnvE1HBLwUnVuunaPOob7dpksI7/v6UnF/rnKGwHf/GdEq9K7iEN7qTtW+S0iivTcGpeTBqqB04wA==" crossorigin="anonymous" />
@stop

@section('plugins.Sweetalert2', true)

@section('title', 'Sliders')

@section('content_header')
    <h1>Sliders</h1>
@stop

@section('content')

<div class="container">
   <div class="row">
       <div class="col-3">
          <a href=" {{ route('sliders.create') }} " class="btn btn-success">Agregar</a>
       </div>
   </div>
    <div class="row">
        @foreach ($sliders as $slider)
            <div class="col-4">
                <div class="card">
                    <img src="{{asset($slider->url)}}" alt="" class="img-fluid">
                    <div class="card-footer">
                         <a href="{{route('sliders.edit', $slider)}}" class="btn btn-primary">Editar</a>
                        <form action="{{route('sliders.destroy', $slider)}}" class="d-inline" method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger" >Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</div>



@stop


@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"  crossorigin="anonymous"></script>
<script>
    // "myAwesomeDropzone" is the camelized version of the HTML element's ID
Dropzone.options.myAwesomeDropzone = {
  headers:{
      'X-CSRF-TOKEN' : "{{csrf_token()}}"
  },
};
</script>
@stop