routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('resultado', [App\Http\Controllers\HomeController::class, 'busqueda'])->name('resultado');
Route::get('vistaprevia', [App\Http\Controllers\HomeController::class, 'vistaprevia'])->name('vistaprevia');
Route::post('gprecios', [App\Http\Controllers\PreciosController::class, 'gprecios'])->name('gprecios.post');
Route::post('tprecios', [App\Http\Controllers\PreciosController::class, 'tprecios'])->name('tprecios.post');
Route::post('lprecios', [App\Http\Controllers\PreciosController::class, 'lprecios'])->name('lprecios.post');
Route::post('clayout', [App\Http\Controllers\TuwallController::class, 'clayout'])->name('clayout.post');
Route::get('carrito', [App\Http\Controllers\HomeController::class, 'carrito'])->name('carrito');
Route::get('confirmacion', [App\Http\Controllers\HomeController::class, 'confirmacion'])->name('confirmacion');
//Route::get('carrito', ['middleware' => 'auth', 'uses' => 'App\Http\Controllers\HomeController@carrito'], [App\Http\Controllers\HomeController::class, 'carrito'])->name('carrito');

Route::get('tuwall', [App\Http\Controllers\TuwallController::class, 'tuwall'])->name('tuwall');
Route::post('cmarco', [App\Http\Controllers\TuwallController::class, 'cmarco'])->name('cmarco');
Route::post('clayout', [App\Http\Controllers\TuwallController::class, 'clayout'])->name('clayout');
Route::get('talentos', [App\Http\Controllers\TalentosController::class, 'talentos'])->name('talentos');
Route::resource('contacto', App\Http\Controllers\ContactoController::class);
Route::get('carga', [App\Http\Controllers\HomeController::class, 'carga'])->name('carga');
Route::resource('registro', App\Http\Controllers\RegistroController::class);
Route::post('registra', [App\Http\Controllers\RegistraController::class, 'registra'])->name('registra.post');


Route::get('/clear-cache', function () {
    echo Artisan::call('config:clear');
    echo Artisan::call('config:cache');
    echo Artisan::call('cache:clear');
    echo Artisan::call('route:clear');
    echo Artisan::call('optimize:clear');
 });


Auth::routes();

Route::group(['prefix' => 'usuario', 'middleware' => ['role:admin|operativo|cliente']], function(){
    Route::get('/', [App\Http\Controllers\Usuario\HomeController::class, 'index']);
    Route::get('confirmacion', [App\Http\Controllers\Usuario\HomeController::class, 'confirmacion']);
    Route::resource('carrito', App\Http\Controllers\Usuario\CarritoController::class);
    Route::resource('cgetty',  App\Http\Controllers\Usuario\CgettyController::class);
    Route::resource('tuwall',  App\Http\Controllers\Usuario\TuwallController::class);
    Route::get('pago', [App\Http\Controllers\Usuario\PagoController::class, 'pago'])->name('pago');
});

Route::get('api', [App\Http\Controllers\Api\GettyController::class, 'getty'])->name('getty');

Route::group(['prefix' => 'admin','middleware' => ['role:admin|operativo|cliente']], function(){
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
    Route::resource('sliders', App\Http\Controllers\Admin\SlidersController::class);
    Route::resource('usuarios', App\Http\Controllers\Admin\UsersController::class);
    Route::get('reportes', [App\Http\Controllers\ReportesController::class, 'index'])->name('reportes');
    Route::resource('atributos', App\Http\Controllers\AtributosController::class);
    Route::get('getty', [App\Http\Controllers\Admin\GettyController::class, 'getty'])->name('api');
    Route::post('search',[App\Http\Controllers\Admin\GettyController::class, 'search'])->name('search.post');
    Route::resource('materiales', App\Http\Controllers\Admin\MaterialesController::class);
    Route::resource('medidas', App\Http\Controllers\Admin\MedidasController::class);
    Route::resource('categorias', App\Http\Controllers\Admin\CategoriasController::class);
    Route::resource('colecciones', App\Http\Controllers\Admin\ColeccionesController::class);
    Route::resource('clientes', App\Http\Controllers\Admin\ClientesController::class);
    Route::resource('tags', App\Http\Controllers\Admin\TagsController::class);
    Route::resource('contact', App\Http\Controllers\Admin\ContactoController::class);
    Route::resource('ordenes', App\Http\Controllers\Admin\OrdenesController::class);
    Route::resource('perfil', App\Http\Controllers\Admin\PerfilController::class);
    Route::get('precios', [App\Http\Controllers\Admin\PreciosController::class, 'index'])->name('precios');
    Route::post('cupon',[App\Http\Controllers\Admin\CuponesController::class, 'cupon'])->name('cupon.post');
    Route::get('cuponera',[App\Http\Controllers\Admin\CuponesController::class, 'index']);
    Route::get('incompletas',[App\Http\Controllers\Admin\OrdenIncompletaController::class, 'index'])->name('incompletas');
    
    
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = [
        'categoria_id',
        'tag_nombre',
        'tag_palabras',
        'tag_estatus'
    ];

    public function categoria()
    {
        return $this->hasOne('App\Models\Categoria', 'id');
    }


}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Categoria;
use App\Models\Slider;
use App\Models\Tag;
use App\Models\Tags;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        $tags = DB::table('tags')
            ->join('categorias', 'tags.categoria_id', '=', 'categorias.id')
            
            ->select('tags.*', 'categorias.categoria_nombre')
            ->get();
      
        return view('admin.ecommerce.tags.index', compact('tags'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::all();
        return view('admin.ecommerce.tags.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $tag = new Tag();
        $tag->categoria_id = $request->categoria_id;
        $tag->tag_nombre = $request->tag_nombre;
        $tag->tag_palabras = $request->tag_palabras;
        $tag->tag_estatus = $request->tag_estatus;

        $tag->save();
        
       // return Redirect::back()->with('actualizar','ok');
        return redirect()->route('tags.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorias = Categoria::all();
        $tags = DB::table('tags')
        ->join('categorias', 'tags.categoria_id', '=', 'categorias.id')
        ->select('tags.*', 'categorias.categoria_nombre')
        ->where('tags.id', '=', $id)
        ->get();

        return view('admin.ecommerce.tags.edit', compact('categorias', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
      $tag = Tag::findOrFail($id);

        $tag->categoria_id = $request->categoria_id;
        $tag->tag_nombre = $request->tag_nombre;
        $tag->tag_palabras = $request->tag_palabras;
        $tag->tag_estatus = $request->tag_estatus;

        $tag->save();

        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::findOrFail($id);

        $tag->delete();

        return redirect()->route('tags.index');
    }   
}

resources/views/admin/ecommerce/tags/create.blade.php
@extends('adminlte::page')

@section('css')
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
@endsection

@section('plugins.Sweetalert2', false)

@section('title', 'Crear Categoría')

@section('content_header')

  
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Etiquetas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="">Home</a></li>
            <li class="breadcrumb-item">Etiquetas</li>
            <li class="breadcrumb-item active">Crear</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@stop

@section('content')

<div class="justify-content-end" >

    
   
 </div>
<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">
            
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Creando nueva etiqueta</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                 <form role="form" action="{{ route('tags.store') }}" method="POST" enctype="multipart/form-data">
                  @csrf
                  <div class="card-body">
                    <div class="form-group">
                        <label for="rol">Categoría superior</label>
                        <select class="form-control"  name="categoria_id" id="">
                         @foreach ($categorias as $categoria)
                        <option value="{{$categoria->id}}">{{$categoria->categoria_nombre}}</option>
                         @endforeach
                        </select>
                      </div>
                    <div class="form-group">
                      <label for="titulo">Título de la etiqueta</label>
                      <input type="text" class="form-control" id="titulo" name="tag_nombre" placeholder="">
                    </div>
                    <div class="form-group">
                      <label for="palabras">Palabras</label>
                      <input type="text" class="form-control" id="palabras" name="tag_palabras" placeholder="palabras">
                    </div>
                    <div class="form-group">
                    <div class="form-check">
                      <input type="checkbox" class="form-check-input" name="tag_estatus" id="exampleCheck1" value="1">
                      <label class="form-check-label" for="exampleCheck1">Activa</label>
                    </div>
                  </div>
                  <!-- /.card-body -->
  
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
                </form>
              </div>
              <!-- /.card -->
           

        </div>
    </div>
</div>
@endsection
@section('js')
   @if (session('actualizar') == 'ok')

<script>
   Swal.fire(
        '¡Excelente!',
        'Los cambios se han realizado',
        'success'
        )
</script>
    
@endif

@stop

resources/views/admin/ecommerce/tags/delete.blade.php
<form id="formulario-borrar" action="{{ route('tags.destroy', $tag )}}" method="POST" style="display:inline-block;">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
</form>

resources/views/admin/ecommerce/tags/edit.blade.php
@extends('adminlte::page')

@section('css')
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
@endsection

@section('plugins.Sweetalert2', false)

@section('title', 'Crear Categoría')

@section('content_header')

  
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Etiquetas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="">Home</a></li>
            <li class="breadcrumb-item">Etiquetas</li>
            <li class="breadcrumb-item active">Crear</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@stop

@section('content')

<div class="justify-content-end" >

    
   
 </div>
<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">
            
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Editar etiqueta</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                 <form role="form" action="{{ route('tags.update', $tags[0]->id) }}" method="POST" enctype="multipart/form-data">
                  @csrf
                  @method('PUT')
                  <div class="card-body">
                    <div class="form-group">
                        <label for="rol">Categoría superior</label>
                        <select class="form-control"  name="categoria_id" id="">
                        <option value="{{ $tags[0]->categoria_id }}">{{ $tags[0]->categoria_nombre }}</option>
                         @foreach ($categorias as $categoria)
                        <option value="{{$categoria->id}}">{{$categoria->categoria_nombre}}</option>
                         @endforeach
                        </select>
                      </div>
                    <div class="form-group">
                      <label for="titulo">Título de la etiqueta</label>
                      <input type="text" class="form-control" id="titulo" name="tag_nombre" value="{{ $tags[0]->tag_nombre }}">
                    </div>
                    <div class="form-group">
                      <label for="palabras">Palabras</label>
                      <input type="text" class="form-control" id="palabras" name="tag_palabras" value="{{ $tags[0]->tag_palabras }}">
                    </div>
                    <div class="form-group">
                    <div class="form-check">
                      <input type="checkbox" class="form-check-input" name="tag_estatus" id="exampleCheck1" value="1">
                      <label class="form-check-label" for="exampleCheck1">Activa</label>
                    </div>
                  </div>
                  <!-- /.card-body -->
  
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
                </form>
              </div>
              <!-- /.card -->
           

        </div>
    </div>
</div>
@endsection
@section('js')
   @if (session('actualizar') == 'ok')

<script>
   Swal.fire(
        '¡Excelente!',
        'Los cambios se han realizado',
        'success'
        )
</script>
    
@endif

@stop

resources/views/admin/ecommerce/tags/index.blade.php
@extends('adminlte::page')

@section('css')
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
@endsection

@section('plugins.Datatables', true)
@section('plugins.Sweetalert2', true)

@section('title', 'Etiquetas')

@section('content_header')

  
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Etiquetas</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="">Home</a></li>
            <li class="breadcrumb-item active">Etiquetas</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@stop

@section('content')

<div class="justify-content-end" >


    <a href=" {{ url('admin/tags/create') }} " class="btn btn-success">Agregar Etiqueta</a>
 </div>
<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">
            

            <!-- Default box -->
            <div class="box"> 
                <div class="box-header with-border">

                  

                </div>
                <div class="box-body">

                  <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Categoría</th>
                            <th>Descripción</th>
                            <th>Estatus</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                        @foreach ($tags as $tag)
                        <tr>
                            <td>{{$tag->id}}</td>
                            <td>{{$tag->tag_nombre }}</td>
                            <td>{{$tag->categoria_nombre }}</td>
                            <td>{{$tag->tag_palabras}}</td>
                            @if ($tag->tag_estatus == 1)
                            <td>Activo</td>
                            @else 
                            <td>Inactivo</td>
                            @endif
                            <td>
                              <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                              <form id="formulario-borrar" action="{{ route('tags.destroy', $tag->id )}}" method="POST" style="display:inline-block;">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                            </form>
                            
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>
</div>
@endsection
@section('js')
<script>
    $(function () {
   
      $('#example2').DataTable({
        'paging'      : true,
        'lengthChange': false,
        'searching'   : true,
        'ordering'    : true,
        'info'        : true,
        'autoWidth'   : false
      })
    })



    $('#formulario-borrar').submit(function(e){
      e.preventDefault();
      Swal.fire({
      title: '¿Seguro que quieres eliminar la categoría?',
      text: "No se podrá recuperar",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: '¡Sí, eliminar!',
      cancelButtonText: 'Cancelar!'
    }).then((result) => {
      if (result.value) {
      
        this.submit();
        }
      })
    });
        
  </script>
@stop